### ISSUE TITLE
i used your code. but i encounter this problem. i don't know why

### ISSUE THREAD

**Issue by chung771026** [klintan/py-nltk-svo#2]
File "C:/Users/kevin/Anaconda2/node-webkit/launcher/NLP.py", line 202, in <module>
    val.append(svo.process_parse_tree(root_tree[0]))

TypeError: 'listiterator' object has no attribute '**getitem**'

**Comment by klintan** [comment]
Hm strange, I will try to set it up and figure out why, might be a new version of NLTK that messes things up.

**Comment by chung771026** [comment]
thanks!! ithought that the nltk's libraries and functions may change.

**Comment by klintan** [comment]
Did a quick fix, it should now work.
